
#server:
#  port: 8443
#  sslPort: 8080
#  ssl:
#    key-store: classpath:any.jks
#    key-password: 214174460510953
#  undertow:
#    worker-threads: 20
#    buffer-size: 512
#    io-threads: 2
#  address: 0.0.0.0
#
#spring:
#  redis:
#    host: 193.112.46.15
#    password: !@#pppqqq
#  datasource:
#    url: jdbc:mysql://193.112.46.15:3306/any_db?useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: !@#pppqqq
#    sql-script-encoding: utf-8
#    hikari:
#      max-lifetime: 1765000
#      maximum-pool-size: 10
#
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#
#logging:
#  config: logback-spring.xml
#  path: logs
#  level: debug

