server:
  address: 0.0.0.0
  port: 8443
  sslPort: 8080
  ssl:
    key-store: classpath:any.jks
    key-password: 214174460510953
  undertow:
    worker-threads: 20
    buffer-size: 512
    io-threads: 2
spring:
  redis:
    host:
    password:
  datasource:
    url: jdbc:mysql://193.112.46.15:3306/any_db?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    sql-script-encoding: utf-8
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10
    driver-class-name: org.mariadb.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml
  path: /logs
  level:
    cn.ictgu: debug
